name: Dev gitbook plugins permissions

on:
  push:
    paths:
      - plugins/**

env:
  OUTPUT_DIRECTORY: output
  GCS_BUCKET: ${{ secrets.GCS_BUCKET_DEVELOP }}
  GCS_PROJECT: ${{ secrets.GCS_PROJECT_DEVELOP }}
  GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEVELOP }}


jobs:
  build-and-deploy:
    name: Dev gitbook plugins permissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          python -m pip install pip==22.3.1
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Create output directory
        run: |-
          mkdir -p $OUTPUT_DIRECTORY
      
      - name: Generate permissions
        run: |
          python main.py
      
      - name: Authenticate to gcloud Kdev
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GCS_SA_KEY }}'

      - name: Setup GoogleCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCS_PROJECT }}

      - name: Deploy
        run: |-
          gsutil -m rsync -R "$OUTPUT_DIRECTORY" gs://$GCS_BUCKET/plugins/
      