name: Dev gitbook plugins permissions

on:
  push:
    paths:
      - plugins/**

env:
  OUTPUT_DIRECTORY: output
  GCS_BUCKET: ${{ secrets.GCS_BUCKET_DEVELOP }}
  GCS_PROJECT: ${{ secrets.GCS_PROJECT_DEVELOP }}
  GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEVELOP }}


jobs:
  build-and-deploy:
    name: Dev gitbook plugins permissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install pip==22.3.1
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Create output directory
        run: |-
          mkdir -p $OUTPUT_DIRECTORY
      
      - name: Find changed files in plugins/
        id: changed-files
        run: |
          # Get the commit before the workflow started
          git fetch origin main
          
          # Show detailed commit information
          echo "GitHub Event Context:"
          echo "Event type: ${{ github.event_name }}"
          echo "Before commit (old state): ${{ github.event.before }}"
          echo "After commit (new state): ${{ github.event.after }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          
          # Compare plugins folder before and after
          echo "Files in plugins folder before:"
          git ls-tree -r --name-only ${{ github.event.before }} -- plugins/
          echo "Files in plugins folder after:"
          git ls-tree -r --name-only ${{ github.event.after }} -- plugins/
          
          # Get changed files in plugins folder
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- plugins/ > changed_files.txt
          echo "Changed files in plugins folder:"
          cat changed_files.txt
          
          # Set output variable with changed files
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          cat changed_files.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Generate permissions
        run: |
          python main.py --changed-files "$(cat changed_files.txt)"
      
      - name: Authenticate to gcloud Kdev
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.GCS_SA_KEY }}'

      - name: Setup GoogleCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCS_PROJECT }}

      - name: Deploy
        run: |-
          gsutil -m cp -r "$OUTPUT_DIRECTORY"/* gs://$GCS_BUCKET/plugins/
      